### ISSUE TITLE
docs: a lot of sections are missing 

### ISSUE THREAD

**Issue by andig** [go-sprout/sprout#45]
### Describe the bug

Anything else than type conversions is not rendered as a proper section on the docs site, but still under "Old documentation from Sprig"
![image](https://github.com/user-attachments/assets/63ed8363-1f86-441f-8631-901f3a34049c)

### Version of software

v0.4.x

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 42atomys** [comment]
Hi @andig,

Yes, the documentation site needs a lot of attention, and type conversions are the only ones I've done at this time!

I left this issue open because it is indeed an issue, but it will serve more as a "feedback" issue for the documentation. I will write proper documentation over time as a full group of functions are migrated.

Thanks for the time according to the project !

**Comment by 42atomys** [comment]
The documentation are updated with the **v0.5.0** https://sprout.atom.codes ✔️ 
Thanks for the report
