### ISSUE TITLE
proposal: initialize a handler with all supported registries

### ISSUE THREAD

**Issue by shashankram** [go-sprout/sprout#73]
### You have a proposal, explain it!

I would like to initialize the handler with all supported [registries](https://docs.atom.codes/sprout/registries/list-of-all-registries)
`handler.AddAllRegistries()` instead of `handler.AddRegistries(std.NewRegistry(), encoding.NewRegistry(), ...)`

### Describe the solution you'd like

-

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by 42atomys** [comment]
Hi @shashankram, thanks for your suggestion.

I understand the desire to include all functions at once in cases where function selection isn’t critical. However, we can't add a function directly to the `sprout` package, as it would disrupt our import optimizations. The cleanest approach would be to create a separate package that registers all registries, providing a one-liner. However, this might not be ideal for the package, as the one-liner would become increasingly overloaded as the number of registries grows.

Possible solutions could be:
- **If the issue is the effort of navigating the documentation for each import path**, we could add a snippet in the documentation containing all paths in one place for convenience.
- **If the challenge is that you need to initialize `sprout` in multiple areas** within your project, perhaps a "registry group" solution would help. This way, you could register all at once and reuse the group (you’d define and add to the group on your side, while we would handle the group API with functions like `NewGroup`, `AddToGroup`, etc.).


Let me know,

**Comment by shashankram** [comment]
I basically want the ability to load all registries. The user shouldn't need to be aware of the individual packages and look up documentation if they want a default setting that just works. Sprout should provide an `AllRegistries()` helper.

**Comment by 42atomys** [comment]
Thank you for your reply. I understand the convenience of having an `AllRegistries()` helper, but there are several reasons why this approach is not feasible directly in the `sprout` package:

1. **Optimization**: Including all registries by default would lead to longer build times and larger binary sizes, which contradicts the goal of `sprout` to be an optimized and efficient package.
2. **Declarative Nature of Go**: Go encourages a declarative approach where you import only what you need. An all-in-one solution does not align with this philosophy.

To make it easier for developers, I will add a snippet on the documentation page [List of All Registries](https://docs.atom.codes/sprout/registries/list-of-all-registries) for quick copy-pasting without impacting the project.

_We will keep the "registry grouping" solution in mind for a future 1.1 release._
