### ISSUE TITLE
Go examples: use ExampleXXX not godoc

### ISSUE THREAD

**Issue by ccoVeille** [go-sprout/sprout#85]
### Please exprime yourself

Right now, code is documented with a lot of godoc. It's good, but the format is not obvious to write and indent

I would like to suggest using go ExampleXXX function

This way you provide code that people can copy paste and use via Go playground.

Take a look at my project
https://github.com/ccoVeille/go-safecast/blob/main/examples_test.go

And look how code is rendered
https://pkg.go.dev/github.com/ccoveille/go-safecast#ToInt8 with its example

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by ccoVeille** [comment]
I thought about it by reading

- https://github.com/go-sprout/sprout/pull/82

**Comment by 42atomys** [comment]
Hi @ccoVeille, 

I think the "example" in godoc aren't in the best place because the code is a `go template example`, So I think for the go template example, we should change it to something like : 
```go
// For an example of this function in a go template, refer to [Sprout Documentaion: toBool].
//
// [Sprout Documentaion: toBool]: https://docs.atom.codes/sprout/registries/conversion#tobool
```
This will increase the readability of the godoc and prevent unmatched or non-runnable examples between the godoc and the documentation. So, only positive things.

And for internal functions, yes, the usage of Example would be nice.
WDYT ?

**Comment by ccoVeille** [comment]
I agree with you. It's OK.

Let's close
